from elasticsearch import Elasticsearch
import json
from datetime import datetime

# Password for the 'elastic' user generated by Elasticsearch
ELASTIC_PASSWORD = "elastic"

# Create the client instance
client = Elasticsearch(
    "https://localhost:9200",
    ca_certs=r"./ElasticSearchDatabase/ca.crt",
    basic_auth=("elastic", ELASTIC_PASSWORD),
    verify_certs=False
)

# client = Elasticsearch(
#   "https://localhost:9200",
#   ca_certs=r"../ElasticSearchDatabase/ca.crt",
#   api_key="U1JSZ0lKTUJTWWk4UHY0anJ4T2s6bjZJbE5sUTRRQ3VSZ0FvVWRmc1lpZw=="
# )
# Successful response!
print(client.info())
print(json.dumps(client.info().body, indent=4))
entry = {
    "image-title": "boxer-dog.jpg",
    "created-timestamp": datetime.now(),
    "last-edited-timestamp": datetime.now(),
    "description": "A boxer dog smiling",
    "perceptual-hash": ""
}

# Put our entry into the elasticsearch database
image_id = entry["image-title"] + "-" + str(entry["created-timestamp"]) # create an id for the image
resp_index = client.index(index="photo-management", id=image_id, document=entry)
print(resp_index['result'])


# Retrieve our entry from the elasticsearch database
print("Retrieving...")
resp_get = client.get(index="photo-management", id="boxer-dog.jpg-2024-11-22 15:53:48.687450")["_source"]
print(json.dumps(resp_get, indent=4))

