import pyttsx3
from elasticsearch import Elasticsearch
import json
from datetime import datetime

# Password for the 'elastic' user generated by Elasticsearch
ELASTIC_PASSWORD = "elastic"

# Create the client instance
client = Elasticsearch(
    "https://localhost:9200",
    ca_certs=r"./ElasticSearchDatabase/ca.crt",
    basic_auth=("elastic", ELASTIC_PASSWORD),
    verify_certs=False
)

class speech:
    def __init__(self):  
        self.engine = pyttsx3.init() #initialize the pyttsx3 engine
    
    def speak(self, text: str):
        """
        Uses pyttsx3 to say the provided text.
        :param text: The string to be read aloud.
        """
        if not isinstance(text, str):
            raise ValueError("input must be string")
        
        self.engine.say(text)
        self.engine.runAndWait()

resp_get = client.get(index="photo-management", id="boxer-dog.jpg-2024-11-22 15:53:48.687450")["_source"]["description"]
print(resp_get)
engine = speech()
engine.speak(resp_get)