from elasticsearch import Elasticsearch
import json
from datetime import datetime
import base64

# Password for the 'elastic' user generated by Elasticsearch
ELASTIC_PASSWORD = "elastic"

# Create the client instance
client = Elasticsearch(
    "https://localhost:9200",
    ca_certs=r"ElasticSearchDatabase\http_ca.crt",
    basic_auth=("elastic", ELASTIC_PASSWORD)
)

# Successful response!
print(json.dumps(client.info().body, indent=4))

# Elastic search suppports binary data through base64 encoding
# This creates a very long string entry in the database entry
TEST_IMAGE_DIR = "test-images/"
with open(f'{TEST_IMAGE_DIR}boxer-dog.jpg', 'rb') as image_file:
    image_data = image_file.read()
base64_encoded = base64.b64encode(image_data).decode('utf-8')

entry = {
    "image-title": "boxer-dog.jpg",
    "timestamp": datetime.now(),
    "image-bin": base64_encoded,
    "description": "A boxer dog smiling"
}

# Put our entry into the elasticsearch database
resp = client.index(index="test-index", id=1, document=entry)
print(resp['result'])


# Retrieve our entry from the elasticsearch database
resp = client.get(index="test-index", id=1)["_source"]
print(json.dumps(resp, indent=4))


# Test that image can be properly decoded and written after retrieval
base64_decoded = base64.b64decode(resp["image-bin"])
with open(f'{TEST_IMAGE_DIR}boxer-dog-2.jpg', 'wb') as image_file:
    image_file.write(base64_decoded)
